pipeline:
    name: simple demo pl
    identifier: simple_demo_pl
    allowStageExecutions: false
    projectIdentifier: git_experience_project
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: approval
              identifier: approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approval
                                identifier: approval
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.paul_group
                                    approverInputs: []
                          - step:
                                type: ShellScript
                                name: bash script
                                identifier: bash_script
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "just making a change"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
              tags: {}
